# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ryr2JjfoOW9ZwEu1jxlg-ARVFv8EyBCT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load dataset
df = pd.read_csv('/content/Titanic-Dataset (2).csv')

# Basic info
print(df.info())             # Data types and non-null values
print(df.describe())         # Descriptive stats
print(df.isnull().sum())     # Missing values in each column

# Histogram for numeric features
df.hist(figsize=(10, 8), bins=20)
plt.tight_layout()
plt.show()

# Boxplots for numeric features
for col in df.select_dtypes(include='number').columns:
    plt.figure(figsize=(6, 2))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.tight_layout()
    plt.show()

# Correlation heatmap
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")

# Pairplot (only for smaller datasets or subset of numeric columns)
sns.pairplot(df.select_dtypes(include='number'))
plt.show()

# Example: scatter plot using Plotly (make sure the columns exist)
if 'Age' in df.columns and 'Fare' in df.columns:
    fig = px.scatter(df, x='Age', y='Fare', color='Survived')  # Example for Titanic dataset
    fig.show()
else:
    print("The columns 'Age', 'Fare', or 'Survived' do not exist in the dataset.")